lab1: main.o
	g++ -g -std=c++11 -Wall main.o -o lab3

main.o: main.cpp DoubleLinkedList.h DoubleLinkedList.hpp Node.h Node.hpp
	g++ -g -std=c++11 -Wall -c main.cpp
clean:
	rm *.o lab3
	echo clean done
